### ISSUE TITLE
Game for the game showcase

### ISSUE THREAD

**Issue by JakInventions** [4ian/GDevelop-website#14]
Hi all!

I made a game made with GDevelop and I think it would be great to have it on the website.

## Screenshots

=>
![screenshot_20180401-174758](https://user-images.githubusercontent.com/39132175/41875879-3a244bf4-789a-11e8-83a8-d65855645bf1.png)
![screenshot_20180518-161243](https://user-images.githubusercontent.com/39132175/41875880-3a3c34da-789a-11e8-883c-f54fd0504089.png)

## Name, links and details

=> 
Name : Jak Inventions

Game Name : Brick Drop

Google Play Link : https://play.google.com/store/apps/details?id=com.inventions.jak.brickdrop

Amazon App Store Link : https://www.amazon.com/Jak-Inventions-Brick-Drop/dp/B07CLB4GY1/ref=sr_1_1?ie=UTF8&qid=1529960726&sr=8-1&keywords=brick+drop

Web Version (Only works on touch screen devices) : https://jakinventions.github.io/BrickDropWebVersion/

**Comment by 4ian** [comment]
Thanks! It's on the website :)

**Comment by JakInventions** [comment]
Thanks a ton for putting it on the showcase, within the first week I got a
few downloads from people I assume came from the fdevelop site, which
really goes a long way
