### ISSUE TITLE
Game for the game showcase

### ISSUE THREAD

**Issue by frolics2dio** [4ian/GDevelop-website#161]
Uphill Climb Racing is just the perfect game for you. True physics make this Game the best Car 2D game on mobile!
**version 1.1.5**

<img src="https://user-images.githubusercontent.com/58515253/99947453-03fe1d00-2d9e-11eb-9770-1d190c8cd303.gif" width="400" height="140"/><img src="https://user-images.githubusercontent.com/58515253/99947464-082a3a80-2d9e-11eb-9cef-88188b22efa2.gif" width="400" height="140"/>

![Screenshots1234](https://user-images.githubusercontent.com/58515253/99948727-de721300-2d9f-11eb-948d-a4b629a14654.jpg)
![Screenshot4](https://user-images.githubusercontent.com/58515253/99943475-5ee04600-2d97-11eb-9918-a4a049682062.jpg)
![Screenshot8](https://user-images.githubusercontent.com/58515253/99943495-67388100-2d97-11eb-9478-33d591dbb7d7.jpg)

## Uphill Climb Racing Neon
YouTube Link: https://youtu.be/YKwz9csWbo8

If you like Car games that can keep you hooked for many hours?
Then Uphill Climb Racing is just the perfect game for you. True physics make this climb racing the best Car 2D sim on mobile! Addictive and entertaining physics based hill race game.

One of the most addictive and entertaining physics based driving game. Offline Uphill Game with various obstacles that will make you addicted, Skip all obstacles on the road, control your Racing Car not to bounce and overturn. All the Levels are created randomly.

**frolics2dio, Uphill Climb Racing Neon**
https://play.google.com/store/apps/details?id=com.frolics2dio.uphillclimb.racing.neon

**Comment by 4ian** [comment]
That's a very nicely made game, congrats :) 
I've added it to https://gdevelop-app.com/games-showcase/

Careful about the description on the Play Store, there are a few typos: 
* "If you like Car games that can keep you hooked for many hours?" => "Searching for a car game that can keep you hooked for many hours?"
* "Press the pedal can acceleration" => Press the pedal to accelerate

Keep up the good work 👍👍

**Comment by frolics2dio** [comment]
Dear Florian Rival,

Thank you very much for considering this game worthy for it and thank you
for the description. I will definitely take care of it from now on.

Thanks and regards,
Frolics2dio.
