### ISSUE TITLE
Game for the game showcase: Sakawochi

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop-website#18]
Hi @4ian ,
my game "Sakawochi" has finally reached a level where it is completely playable, so I decided to release it as in development on Itch, Gamejolt and Ubuntu Touch OpenStore.

## Screenshots
Pick what ever you like for the website. If you need a certain size please let me know.
![sakawochi_aquarium](https://user-images.githubusercontent.com/7413059/43992765-74e8b316-9d83-11e8-83f2-9953e967676c.png)
![sakawochi_asset_store](https://user-images.githubusercontent.com/7413059/43992766-75017554-9d83-11e8-92e6-943a8218809b.png)
![sakawochi_choose_language](https://user-images.githubusercontent.com/7413059/43992767-7517dc72-9d83-11e8-9f03-45fcf8fe3633.png)
![sakawochi_fish_details](https://user-images.githubusercontent.com/7413059/43992768-752e3a80-9d83-11e8-9832-f7e75885cf6e.png)
![sakawochi_cover_image_wide](https://user-images.githubusercontent.com/7413059/43992770-825fbe40-9d83-11e8-97d3-f955e9e8dfee.png)
![sakawochi_page_background](https://user-images.githubusercontent.com/7413059/43992771-97d702e2-9d83-11e8-9206-19831ab02c7a.png)
![sakawochi_page_header](https://user-images.githubusercontent.com/7413059/43992776-a1f9c2d2-9d83-11e8-8455-07f5f2ef20f5.png)
![sakawochi_page_title](https://user-images.githubusercontent.com/7413059/43992778-a4d28ca0-9d83-11e8-8871-ed44cd52886c.png)

## Name, links and details

**Author:**
Matthias Meike (Wend1go)

**Title:** 
Sakawochi

**Short description:** 
The micro aquarium that fits into your pocket

**Detailed description:** 
Have you ever dreamed of having an aquarium that you can take with you everywhere you go, but that pesky tank just didn't want to fit into your pocket? Than I have good news for you, this game is exactly what you were looking for!

Sakawochi is a real time aquarium simulation. What that means is that the game goes on even if you close the App. Take care of your fish and feed it at least once per day to make them happy and grow.

The bigger your fish the more it is worth. Sell your little darlings when they grew up to earn coins which you can spend on other types of fish or decorations for your aquarium.

**Platforms:**
Desktop: Linux, OSX, Windows
Mobile: Android, Ubuntu Touch

**Download links:**
[https://wend1go.itch.io/sakawochi](https://wend1go.itch.io/sakawochi)
[https://gamejolt.com/games/sakawochi/353685](https://gamejolt.com/games/sakawochi/353685)
[https://open-store.io/app/sakawochi.wendigosoft](https://open-store.io/app/sakawochi.wendigosoft)

**Comment by 4ian** [comment]
Looks gorgeous! Will add it to the website and try it tomorrow :)

**Comment by Wend1go** [comment]
Thanks :)

By the way:
I reworked the localization system so that it reads json based translation files located in the project directory. Is it possible to bundle these together with the rest of the uploaded project files for the build service somehow?
Currently I need to copy them manually but since I haven't yet been able to build for android myself this would be very handy.
Outsourcing the language files also removed all texts from the preview. Could you tell me where the temp directory is located from where the preview is launche? So that I can copy the language files there manually.

**Comment by 4ian** [comment]
The temporary directory is usually printed in the developer console (`View` > `Toggle Developer Console`):

![image](https://user-images.githubusercontent.com/1280130/44051374-f7344990-9f39-11e8-80dc-2714bb72de52.png)
(Copying all ressources from XXX to YYY - YYY is the preview directory).

A better long term solution would be to allow JSON/custom files resources.

**Comment by 4ian** [comment]
It's up on https://gdevelop-app.com/games-showcase/ :)
Good job on this game :)

**Comment by Wend1go** [comment]
Thank you very much. GD5 is coming along pretty nicely. With search&replace now merged, the usability should be even better. Using the new IDE a lot of fun. :+1: 

I was able to "trick" the IDE so that it copies the json files by manually adding them as audio resource to the project file. They now get properly copied on preview/export.

**Comment by 4ian** [comment]
> I was able to "trick" the IDE so that it copies the json files by manually adding them as audio resource to the project file. They now get properly copied on preview/export.

Nice trick ;) I'll see what I can do later for adding JSON files. How do you do to access to the files in the project directory?

(closing the issue as the game is added on the website)
