### ISSUE TITLE
Download links other than Windows can't be reached without JavaScript

### ISSUE THREAD

**Issue by onpon4** [4ian/GDevelop-website#2]
From what I can gather, it seems what needs to be done to fix this is all those divs with the "tab-pane fade" class should be "tab-pane fade in active" by default, and changed to "tab-pane fade" with JavaScript. Or maybe something with a noscript tag.

**Comment by 4ian** [comment]
Ah sorry didn't find that you posted this before! Yup I'll try to change it.

**Comment by 4ian** [comment]
This should be fixed in the new website version :) https://gdevelop-app.com/download/
Closing this now
