### ISSUE TITLE
[GD5 Web IDE] Preview not working

### ISSUE THREAD

**Issue by Wend1go** [4ian/GDevelop-website#22]
I ran some examples from the new example page on the website. The Project loads in the online IDE, upon hitting the preview button the new tab appears But the preview just shows a black screen with the loading counter in the lower left corner. When it reaches 100% nothing happens.
I can reproduce this with Firefox, Chromium and Chrome on Linux.
![gd5_preview](https://user-images.githubusercontent.com/7413059/45257684-7c898680-b3aa-11e8-935b-7ef129ad0f7d.png)

**Comment by 4ian** [comment]
Oops, got confused with some experiments that I did and uploaded a wrong version. Fixed now! Thanks for letting me know :)
