### ISSUE TITLE
Game for the game showcase

### ISSUE THREAD

**Issue by aidinyildiz** [4ian/GDevelop-website#25]
Hi all!

I made a game made with GDevelop and I think it would be great to have it on the website.

## Screenshots

![yb1](https://user-images.githubusercontent.com/25145245/48967945-2d421200-eff9-11e8-95db-9d179ba615a3.png)
![yb4](https://user-images.githubusercontent.com/25145245/48967949-33d08980-eff9-11e8-9a8f-dbcfeb993b29.png)
![yb3](https://user-images.githubusercontent.com/25145245/48967950-34692000-eff9-11e8-9938-0b6f36ba36f1.png)
![yb2](https://user-images.githubusercontent.com/25145245/48967951-34692000-eff9-11e8-8cdb-9b61be2fbe80.png)

## Name, links and details

NAME OF THE GAME IS : YELLOW BUS.
LINK TO THE GAME IS : https://northstarstudio.itch.io/yellow-bus
It is an Arcade game just for fun

Collect passengers up to 20 
Let passengers left the bus on bus stops
Avoid crazy drivers
Pass other cars to collect score

=> Please enter here your name, the game name and a link to download or play to it.
AYDIN YILDIZ & AKIN YILDIZ, YELLOW BUS, https://northstarstudio.itch.io/yellow-bus

**Comment by 4ian** [comment]
It's up on https://gdevelop-app.com/games-showcase :)
