### ISSUE TITLE
Game for the game showcase

### ISSUE THREAD

**Issue by MichaelJHatena** [4ian/GDevelop-website#39]
Hi all!

I made a 3D pool game with GDevelop and I think it would be great to have it on the website.

## Screenshots
![Super Billard 2019-03-10 12-21-15-26](https://user-images.githubusercontent.com/38227809/54239265-fbf34080-451a-11e9-846b-612d3bd16069.png)
![Super Billard 2019-03-10 12-23-16-88](https://user-images.githubusercontent.com/38227809/54239288-10373d80-451b-11e9-9c08-73cef4168106.png)
![Super Billard 2019-03-10 12-23-26-07](https://user-images.githubusercontent.com/38227809/54239295-15948800-451b-11e9-94f0-404ad6f3ab8f.png)
![Super Billard 2019-03-10 12-24-25-46](https://user-images.githubusercontent.com/38227809/54239303-1b8a6900-451b-11e9-9102-163a9ca071af.png)

**Comment by 4ian** [comment]
🤯😳

Can't believe my eyes!
I'll add it for sure on the website  😃

This is super impressive. I guess I really have to port the 3D object to GDevelop 5 ;)

**Comment by MichaelJHatena** [comment]
is it possible to optimised more the performances with the 3D objects in
GD5 ? :)

Le mer. 13 mars 2019 à 01:43, Florian Rival <notifications@github.com> a
écrit :

**Comment by 4ian** [comment]
Well for now there is no even a 3D object ;) GD won't turn into a full featured 3D engine, but if I introduce some 3d Objects/3d meshes, I'll try to work on making it optimized. Although you'll never get the same performance as a real 3d engine, doing optimization like frustrum culling.

**Comment by blurymind** [comment]
how did you make it 3d? Are you using threejs?

**Comment by 4ian** [comment]
The 3D Box Object from GDevelop 4 I think + clever mathematical computations :)

**Comment by eddOrnelas** [comment]
how you add 3D Box Object to GDevelop 5?

**Comment by 4ian** [comment]
You can't for now. Vote for this feature request here: https://trello.com/c/EiG3yzhM/105-add-3d-box-objects or develop an extension yourself and submit it to me :)

**Comment by 4ian** [comment]
(Finally) added to the website! :)
