### ISSUE TITLE
Smash The Eggs for game showcase

### ISSUE THREAD

**Issue by xiscoj** [4ian/GDevelop-website#41]
Hi all!

I made/know a game made with GDevelop and I think it would be great to have it on the website.

## Screenshots

![Screenshot_2019-03-27-15-11-53-936_com xiscosoft CrackEgg](https://user-images.githubusercontent.com/10528128/55157779-8ebbee00-515d-11e9-8534-38d8bb07e29d.png)
![Menu1024x600](https://user-images.githubusercontent.com/10528128/55157827-aeebad00-515d-11e9-89b6-f3077e561568.png)

## Name, links and details

Hi, I'm Francisco Nacher, and I've developed this game basically for children but at the end are parents who most play.
You have to kill all the eggs before new chickens are born, when you reach 30 chicken the game is over.
You can download it from Google Play 
https://play.google.com/store/apps/details?id=com.xiscosoft.CrackEgg

**Comment by 4ian** [comment]
Nice :) Added on my todo list.

**Comment by xiscoj** [comment]
thank I'll continue improving it :-)

**Comment by 4ian** [comment]
(Finally) added to the website! :)
