### ISSUE TITLE
Game for the game showcase

### ISSUE THREAD

**Issue by XxNomadNatanxX** [4ian/GDevelop-website#52]
Hello, I would like to make my game fully made available on Gdevelop 4, it was really cool and visually beautiful, I think it deserves to be on the site :)

It has already been published in Itchio and also in the GameJolt (Demo Version), links below:

https://gamejolt.com/games/Armaduradeoriondemo/389069

https://nomad-natan.itch.io/armor-of-orion-armadura-de-orion

Thanks!

![639624-v4(1)](https://user-images.githubusercontent.com/51864436/59556114-ab650680-8f93-11e9-85cf-e36e84ae12a0.jpg)

![639622-v4](https://user-images.githubusercontent.com/51864436/59556117-b455d800-8f93-11e9-81a1-19c62952086a.jpg)

**Comment by 4ian** [comment]
Looks really cool :) Added on my to do list!

**Comment by 4ian** [comment]
Finally added, thanks! :)

**Comment by XxNomadNatanxX** [comment]
Thank you so much for show my game ;)

Em Qui, 15 de ago de 2019 01:46, Florian Rival <notifications@github.com>
escreveu:
