### ISSUE TITLE
Game for the game showcase

### ISSUE THREAD

**Issue by taqzwee** [4ian/GDevelop-website#65]
Hi all!

I made/know a game made with GDevelop and I think it would be great to have it on the website.

## Screenshots

![PicsArt_10-13-06 28 21](https://user-images.githubusercontent.com/55804404/66709734-a757c280-ed94-11e9-83ff-9e6e3e77d555.jpg)

![PicsArt_10-13-06 30 58](https://user-images.githubusercontent.com/55804404/66709736-b3dc1b00-ed94-11e9-918a-b72243b55058.jpg)

![PicsArt_10-13-06 31 46](https://user-images.githubusercontent.com/55804404/66709745-be96b000-ed94-11e9-8e94-09f3eb4a1f86.jpg)

![PicsArt_10-13-06 45 55](https://user-images.githubusercontent.com/55804404/66709749-c9e9db80-ed94-11e9-8b44-2abd7cfb14a3.jpg)

## Name, links, and details

Space Tappers, https://taqzwee.itch.io/space-tappers, Space Tappers is a shoot'em up game with simple control in a retro arcade style that easy to play but hard to master.

**Comment by 4ian** [comment]
Looks really nice! Let me try it and add it to the website. Great job!

**Comment by 4ian** [comment]
Finally added to website! :)
